### ISSUE TITLE
Differentiate display of multiple translations in annotation editor

### ISSUE THREAD

**Issue by srdee** [PerseusDL/perseids_docs#112]
With multiple new translations of a work, be able to distinguish which is which when creating a new annotation in the annotation editor. 

![translationselection](https://cloud.githubusercontent.com/assets/3961929/2778989/00392e5e-caf8-11e3-8cfa-d79399ba9fef.png)

**Comment by balmas** [comment]
deployed 9-Feb-2015. Use "Rename" link the publication overview to rename a translation.
