### ISSUE TITLE
Be able to re-name texts within the the display

### ISSUE THREAD

**Issue by srdee** [PerseusDL/perseids_docs#143]
Need a human-readable mechanism for distinguishing between multiple new alignments--ability to rename the "Publication" only within the user display, or to preview the first sentence of the publication from within user homepage, etc. 
![display](https://cloud.githubusercontent.com/assets/3961929/3312556/32d9fd04-f6d4-11e3-95e9-10f7a8b4d5c9.jpg)

**Comment by balmas** [comment]
deployed 9-Feb-2015. In the Publication Overview, you can choose "Rename" for a translation and change the translation file's title.
