### ISSUE TITLE
Alignment: change name of publication

### ISSUE THREAD

**Issue by nevenjovanovic** [PerseusDL/perseids_docs#157]
Small issue: it would be nice to have a way to add name of alignment publication later (I forget to do this when creating the alignment).

**Comment by balmas** [comment]
we should allow this for treebank files too

**Comment by balmas** [comment]
the fix in 7bc0f12 makes it possible to change the title for treebank and alignment documents. Note though that these titles are currently only used by the SoSOL app and not carried forth with the publication when it is commit into the git repo.  See #214

**Comment by balmas** [comment]
This is deployed now.  @gcelano and @nevenjovanovic you can now rename translation alignments and treebank documents in Perseids using the "ChangeTitle" link from the Edit and Preview displays (i.e. the sentence list)
