### ISSUE TITLE
Citation scheme not appearing for Iliad translations in annotation interface

### ISSUE THREAD

**Issue by srdee** [PerseusDL/perseids_docs#232]
Only displays 'From' and 'To' without offering book/line options

**Comment by srdee** [comment]
Seems to only be true of the Iliad, but true for multiple user accounts. An issue with the inventory>

**Comment by balmas** [comment]
darn darn darn. an old bug on creation of the cts inventory elements for the new translation snuck back in somehow -- the validate element is enclosing the citationMapping element.  Should be fixed now but I will have to go in and find and fix any student publications that were affected.  I will do this tomorrow am.

**Comment by balmas** [comment]
Ok, publications created after the bug was reintroduced should be fixed now.  I'm closing this item but let me know if any other problems persist.
