### ISSUE TITLE
ADD HOMERIC HYMN TO DEMETER ASAP FOR GREG'S HOMER CLASS

### ISSUE THREAD

**Issue by srdee** [PerseusDL/perseids_docs#241]

**Comment by balmas** [comment]
@srdee -- I assume you want this in Pilots so that students can create their translations... I will try to get it in tomorrow, but just FYI, when the new translation alignment input form goes live, they will also be able to select it there and create a new translation directly as an alignment

**Comment by srdee** [comment]
@balmas yup! exactly! but I can do the inv entry! Great to know abt the alignment form though!

**Comment by srdee** [comment]
@balmas but since they're creating a whole new translation and then aligning that, the alignment editor input form changes won't effect their workflow anyway, will they?

**Comment by balmas** [comment]
@srdee it won't affect their workflow if they want to create a TEI translation no. The new input form just makes it easier for people to create translations of existing texts directly via the alignment editor, without first preserving them as TEI.

**Comment by balmas** [comment]
I've added it to pilots now and make the text available in Perseids. So I think we can close this!

**Comment by srdee** [comment]
Awesome thanks!!!
